name: DPWT Leaderboard Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # alle 4 Stunden

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps chromium

      - name: Run DPWT Leaderboard Watcher
        run: |
          python ms_leaderboard_bot.py || true

      - name: Upload Debug Logs
        uses: actions/upload-artifact@v4
        with:
          name: dpwt-debug-${{ github.run_id }}
          path: |
            *.log
            last_run_state.json
