name: DPWT Marcel Schneider → Discord

on:
  schedule:
    # Alle 30 Minuten starten – das Script selbst drosselt auf 2h, außer wenn live.
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  check-dpwt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Playwright + requests)
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Run monitor (Playwright)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DEBUG: "1"
        run: |
          python dpwt_monitor_discord_playwright.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "update(dpwt): state/log/baseline"
            git push
          fi
