name: DPWT Leaderboard Watcher

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"      # alle 3 Stunden
    - cron: "30 1-23/3 * * *"  # 90 Minuten versetzt (1:30, 4:30, 7:30, ...)

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # für Auto-Commit von logs/state

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (requests + playwright)
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4 playwright

      # KEIN HTML-SCRAPING – wir brauchen nur Browser für Same-Origin fetch
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run watcher
        env:
          DISCORD_WEBHOOK_2: ${{ secrets.DISCORD_WEBHOOK_2 }}
        run: |
          python ms_leaderboard_bot.py || true

      - name: Commit logs & state back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "DPWT watcher: update logs/state [skip ci]"
          file_pattern: |
            logs/last_run.log
            state/state_dpwt.json
