name: DPWT Leaderboard Watcher

on:
  workflow_dispatch:
  schedule:
    # 1) Einmal t채glich zum Einsammeln des n채chsten Turniers + Pre-Event-Ping
    - cron: "07 5 * * *"
    # 2) Alle 30 Minuten (w채hrend Turnieren f체r Round-Status)
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run bot
        env:
          DPWT_PLAYER_ID: "35703"
          DPWT_TOUR_SLUG: "dpworld-tour"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_WEBHOOK_2: ${{ secrets.DISCORD_WEBHOOK_2 }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          python ms_leaderboard_bot.py || true

      - name: Upload logs & JSON reports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: dpwt-debug-${{ github.run_id }}
          path: |
            reports/logs/*.log
            reports/*.json
            reports/snapshots/**
