name: DPWT Leaderboard Watcher

on:
  workflow_dispatch:
  schedule:
    # 1) Täglicher Scan der Profilseite (Erkennung + 2-Tage-Reminder)
    - cron: "7 7 * * *"
    # 2) Optional: Alle 30 Min. (wenn du später die LB-Logik aktivierst)
    # - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run watcher
        env:
          PLAYER_SLUG: "marcel-schneider-35703"
          TOUR_SLUG: "dpworld-tour"
          DISCORD_WEBHOOK_ANNOUNCE: ${{ secrets.DISCORD_WEBHOOK_ANNOUNCE }}
          DISCORD_WEBHOOK_SECOND:   ${{ secrets.DISCORD_WEBHOOK_SECOND }}
          # Optional: Eigener UA
          # USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
        run: |
          python ms_leaderboard_bot.py || true

      - name: Upload logs & reports
        uses: actions/upload-artifact@v4
        with:
          name: dpwt-debug-${{ github.run_id }}
          path: |
            logs/**
            snapshots/**
            reports/**
          if-no-files-found: warn
