name: DPWT Leaderboard Watcher

on:
  schedule:
    # 1) Täglicher Scan (Spieler-Seite) – 07:05 UTC
    - cron: "5 7 * * *"
    # 2) 30-Minuten-Loop für Live – dein Code beendet sich sofort,
    #    wenn kein aktives Event-Fenster erkannt wird
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Leaderboard Bot
        env:
          DISCORD_WEBHOOK_LIVE: ${{ secrets.DISCORD_WEBHOOK_LIVE }}   # <- zweiter Webhook
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          STATE_ISSUE_NUMBER: ${{ vars.STATE_ISSUE_NUMBER }}          # selbe Issue-ID wie vorher
          RELAY_BASE: ${{ secrets.RELAY_BASE }}                       # optional, z.B. Cloudflare Worker
          PLAYER_ID: "35703"
          PLAYER_PAGE: "https://www.europeantour.com/players/marcel-schneider-35703/?tour=dpworld-tour"
          RESULTS_URL: "https://www.europeantour.com/api/v1/players/35703/results/2025/"
        run: |
          python ms_leaderboard_bot.py
