name: DPWT Leaderboard Watcher

on:
  schedule:
    - cron: "0 6 * * *"   # täglich 06:00 UTC (07:00/08:00 Deutschland)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps chromium

      - name: Run MS Leaderboard Watcher
        env:
          DISCORD_WEBHOOK_MS: ${{ secrets.DISCORD_WEBHOOK_MS }}
        run: |
          python ms_leaderboard_bot.py || true

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: dpwt-debug-${{ github.run_id }}
          path: |
            dpwt_watcher_*.log
            last_run.json
