name: DPWT Marcel Schneider → Discord

on:
  schedule:
    # Alle 30 Minuten (Script drosselt intern auf 2h, wenn kein Live-Event läuft)
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  check-dpwt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python dpwt_monitor_discord.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "update(dpwt): state/log/baseline"
            git push
          fi
